title: David Lattimer # your name (or website title) here
logo: "/images/picture.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/davidlattimerjr/">View My LinkedIn Profile</a>
  <br>
  <a href="https://canopenerinacan.github.io/about_me">About Me</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
