title: David Lattimer # your name (or website title) here
logo: "/images/picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This is the coursework from my data science masters from Bellevue University.
  <br><br>
  <a href="https://www.linkedin.com/in/davidlattimerjr/">View My LinkedIn Profile</a> 
    <br><br>
  
theme: jekyll-theme-slate
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
